check50:
  files: &check50_files
    - !exclude "*"
    - !include "*.c"
    - !include "*.h"
    - !include "*.md"
    - !exclude corrector.c
    - !require diccionario.c

submit50:
  files: *check50_files
